name: Build Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: GOOS=windows GOARCH=amd64 make build
      - uses: actions/upload-artifact@v4
        with:
          name: zen-windows-x64
          path: dist/zen.exe
